#!/bin/bash -l
#SBATCH --job-name=prep_2
###SBATCH --output=$PWD/slurm-%A.out
###SBATCH --chdir=/projects/ilfgrid/apps/alphafold-2.3.1/                    # change location to the install directory
#SBATCH --partition=standard                                                 # the queue you submit to
#SBATCH --mem=20G                                                            # the amount of memory to reserve
#SBATCH --ntasks=4                                                          # combined with --cpus-per-task it determines
#SBATCH --cpus-per-task=1                                                    # the number of cpus to use
#SBATCH --nodes=1                                                            # no. of nodes to use
#SBATCH --exclude=ilfgridgpun02fl
#SBATCH --dependency=singleton

echo ">> Job started at: $(date)"
echo "   On Machine:     $(hostname)"
echo -e "   In directory:   $(pwd)\n"
echo -e ">> GPU is "${SLURM_JOB_GPUS}"\n"
start=`date +%s`

WDIR="$PWD"
FASTAFILE="$WDIR/gnrhr_mouse-1162.fasta"

AF_DIR="/projects/ilfgrid/apps/alphafold-2.3.1"
AFDB_DIR="/projects/ilfgrid/data/alphafold-genetic-databases//"
module load miniconda
conda activate $AF_DIR/AF_2.3.1_conda_env

cd $AF_DIR && /projects/ilfgrid/apps/alphafold-2.2.0/prep_MSAs.sh -d $AFDB_DIR -n 4 -m 20 -o $WDIR/ -f $FASTAFILE

BASENAME=`basename $FASTAFILE .fasta`


end=`date +%s`
runtime=$((end-start))
echo -e "\n>> Job finished at: $(date)"
echo -e "\n>> Runtime: $runtime s"